# Generated by Django 3.2.6 on 2021-08-28 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210728_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=main.models.default_creater, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
